### PR TITLE
171 make faq with deleting resultslog for blech run processpy

### PR DESCRIPTION
**Pull request by Mraymon5**
Adds a bit of code that allows blech_run_process.sh to find and overwrite (if desired) results.log.

Also slightly tweaks some of the interface text in belch_exp_info.py, just to try to make a more consistent format. No functional changes, purely aesthetic.

### CODE REVIEW

**Comment by abuzarmahmood** [comment]
Thanks for the update @Mraymon5 !
Have you tested the updated blech_run_process to confirm that it behaves as expected when log file is and is not present?

**Comment by Mraymon5** [comment]
Yeah, it works in my hands

**Review by abuzarmahmood — APPROVED** [review]
Looks good to me

**Comment by abuzarmahmood** [comment]
> Yeah, it works in my hands

Thanks! Merging

**Pull request merged**
